-- =============================================================================
-- crucible — monkey_crucible.workflow_template
-- =============================================================================
-- Named, reusable workflow definitions. A template is instantiated as a task.
-- Run order: 003 (depends on 000_schema.sql)
-- =============================================================================

CREATE TABLE IF NOT EXISTS monkey_crucible.workflow_template (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT        NOT NULL,
  slug        TEXT        NOT NULL UNIQUE,
  description TEXT,
  enabled     BOOLEAN     NOT NULL DEFAULT true,
  weight      INT         NOT NULL DEFAULT 100,   -- lower = higher priority vs other workflows
  metadata    JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Seed: built-in workflow templates
-- ---------------------------------------------------------------------------

INSERT INTO monkey_crucible.workflow_template (name, slug, description, weight)
VALUES
  ('Full Ingest',   'full_ingest',  'Complete pipeline from raw file to published video', 100),
  ('Scrape Only',   'scrape_only',  'Scrape metadata and refine title only',              100),
  ('Encode Only',   'encode_only',  'Encode, generate HLS, and validate',                 100),
  ('Validation',    'validation',   'Run validation step only',                           100),
  ('File Cleanse',  'file_cleanse', 'Clear temp files and archive completed tasks',        50),
  ('Sync Local',    'sync_local',   'Copy file to local, validate, then sort',            100),
  ('Scan',          'scan',         'Backlog init, validate, and draft video record',      100)
ON CONFLICT (slug) DO UPDATE SET
  name        = EXCLUDED.name,
  description = EXCLUDED.description,
  weight      = EXCLUDED.weight;
