-- =============================================================================
-- crucible — monkey_crucible.workflow_step
-- =============================================================================
-- Ordered steps within a workflow template. step_order uses gaps (10, 20, 30)
-- to allow insertion without renumbering. is_final marks the terminal step.
-- Run order: 004 (depends on 002 task_type_registry, 003 workflow_template)
-- =============================================================================

CREATE TABLE IF NOT EXISTS monkey_crucible.workflow_step (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  workflow_id     BIGINT      NOT NULL REFERENCES monkey_crucible.workflow_template(id) ON DELETE CASCADE,
  task_type       TEXT        NOT NULL REFERENCES monkey_crucible.task_type_registry(slug),
  step_order      INT         NOT NULL,           -- explicit sequence; use gaps (10, 20, 30…)
  label           TEXT,
  is_final        BOOLEAN     NOT NULL DEFAULT false,
  is_heavy        BOOLEAN     NOT NULL DEFAULT false,
  is_schedulable  BOOLEAN     NOT NULL DEFAULT false,
  is_manual       BOOLEAN     NOT NULL DEFAULT false, -- human gate: task parks at 'waiting', no handler runs
  weight          INT         NOT NULL DEFAULT 100,
  retry_limit     INT         NOT NULL DEFAULT 0,
  timeout_seconds INT,                             -- null = inherit from task_type_registry default
  config          JSONB       NOT NULL DEFAULT '{}', -- merged into task.metadata at runtime (step wins)
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (workflow_id, step_order)
);

CREATE INDEX IF NOT EXISTS idx_workflow_step_workflow_order
  ON monkey_crucible.workflow_step (workflow_id, step_order);

-- ---------------------------------------------------------------------------
-- Seed: full_ingest
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT;
BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'full_ingest';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final, is_heavy, is_manual)
  VALUES
    (wf_id, 'backlog',          10,  'Backlog',          false, false, false),
    (wf_id, 'rename',           20,  'Rename',           false, false, false),
    (wf_id, 'adjust',           25,  'Adjust',           false, false, true),
    (wf_id, 'dispatch',         30,  'Dispatch',         false, false, false),
    (wf_id, 'draft_video',      40,  'Draft Video',      false, false),
    (wf_id, 'sort',             50,  'Sort',             false, false),
    (wf_id, 'encode',           60,  'Encode',           false, true),
    (wf_id, 'generate_hls',     70,  'Generate HLS',     false, true),
    (wf_id, 'scrape',           80,  'Scrape',           false, false),
    (wf_id, 'refine_title',     90,  'Refine Title',     false, false),
    (wf_id, 'generate_preview', 100, 'Generate Preview', false, true),
    (wf_id, 'validate',         110, 'Validate',         false, false),
    (wf_id, 'publish',          120, 'Publish',          true,  false)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;

-- ---------------------------------------------------------------------------
-- Seed: scrape_only
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT; BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'scrape_only';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final)
  VALUES
    (wf_id, 'scrape',       10, 'Scrape',       false),
    (wf_id, 'refine_title', 20, 'Refine Title', false),
    (wf_id, 'validate',     30, 'Validate',     true)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;

-- ---------------------------------------------------------------------------
-- Seed: encode_only
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT; BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'encode_only';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final, is_heavy)
  VALUES
    (wf_id, 'encode',       10, 'Encode',       false, true),
    (wf_id, 'generate_hls', 20, 'Generate HLS', false, true),
    (wf_id, 'validate',     30, 'Validate',     true,  false)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;

-- ---------------------------------------------------------------------------
-- Seed: validation
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT; BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'validation';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final)
  VALUES (wf_id, 'validate', 10, 'Validate', true)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;

-- ---------------------------------------------------------------------------
-- Seed: file_cleanse
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT; BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'file_cleanse';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final, is_schedulable)
  VALUES
    (wf_id, 'temp_file_clear', 10, 'Clear Temp Files', false, true),
    (wf_id, 'task_clear',      20, 'Clear Tasks',      true,  true)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;

-- ---------------------------------------------------------------------------
-- Seed: sync_local
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT; BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'sync_local';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final)
  VALUES
    (wf_id, 'sort',     10, 'Sync Local', false),
    (wf_id, 'validate', 20, 'Validate',   false),
    (wf_id, 'sort',     30, 'Sort',       true)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;

-- ---------------------------------------------------------------------------
-- Seed: scan
-- ---------------------------------------------------------------------------

DO $$
DECLARE wf_id BIGINT; BEGIN
  SELECT id INTO wf_id FROM monkey_crucible.workflow_template WHERE slug = 'scan';
  INSERT INTO monkey_crucible.workflow_step (workflow_id, task_type, step_order, label, is_final)
  VALUES
    (wf_id, 'backlog',     10, 'Backlog',     false),
    (wf_id, 'validate',    20, 'Validate',    false),
    (wf_id, 'draft_video', 30, 'Draft Video', true)
  ON CONFLICT (workflow_id, step_order) DO NOTHING;
END $$;
