-- =============================================================================
-- crucible — monkey_crucible.task
-- =============================================================================
-- Core task table. One row per task instance. Links to a workflow template,
-- tracks the current step, holds the processor lock, and carries a metadata
-- scratchpad. Cross-schema FK to public.video (video stays in public schema).
--
-- public.task (old system) and monkey_crucible.task (Crucible) coexist during
-- the transition. Old system writes public.task; Crucible writes here.
--
-- Run order: 005 (depends on 001 processor, 003 workflow_template, 004 workflow_step)
-- =============================================================================

CREATE TABLE IF NOT EXISTS monkey_crucible.task (
  id                    BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- entity links (video stays in public schema — cross-schema FK is valid)
  video_id              BIGINT      REFERENCES public.video(id),
  file                  TEXT,

  -- workflow tracking
  workflow_template_id  BIGINT      REFERENCES monkey_crucible.workflow_template(id),
  current_step_id       BIGINT      REFERENCES monkey_crucible.workflow_step(id),

  -- status
  status                TEXT        NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','paused','disabled','hidden','completed','failed','cancelled')),
  step_status           TEXT        NOT NULL DEFAULT 'pending'
    CHECK (step_status IN ('pending','running','success','failed','skipped','waiting')),

  -- processor assignment & locking (FK to public.processor — monkey_crucible.processor is a view)
  processor_id          BIGINT      REFERENCES public.processor(id),  -- null = any
  locked_by             BIGINT      REFERENCES public.processor(id),  -- current holder
  locked_at             TIMESTAMPTZ,

  -- scheduling
  schedule_type         TEXT        NOT NULL DEFAULT 'once'
    CHECK (schedule_type IN ('once','cron')),
  frequency             TEXT,                              -- cron expression
  next_execution        TIMESTAMPTZ,
  last_executed_at      TIMESTAMPTZ,

  -- priority
  weight                INT         NOT NULL DEFAULT 100,  -- lower = higher priority

  -- flags
  enabled               BOOLEAN     NOT NULL DEFAULT true,
  manual_mode           BOOLEAN     NOT NULL DEFAULT false, -- only run when explicitly triggered
  sorted                BOOLEAN     NOT NULL DEFAULT false,

  -- state
  attempt_count         INT         NOT NULL DEFAULT 0,
  metadata              JSONB       NOT NULL DEFAULT '{}',  -- config scratchpad
  result                JSONB       NOT NULL DEFAULT '{}',  -- last step result snapshot

  -- audit
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at          TIMESTAMPTZ
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_task_queue
  ON monkey_crucible.task (locked_by, weight, updated_at)
  WHERE status = 'active' AND step_status = 'pending' AND enabled = true;

CREATE INDEX IF NOT EXISTS idx_task_status_step
  ON monkey_crucible.task (status, step_status)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_task_processor
  ON monkey_crucible.task (processor_id)
  WHERE processor_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_task_next_execution
  ON monkey_crucible.task (next_execution)
  WHERE schedule_type = 'cron' AND status = 'active';

CREATE INDEX IF NOT EXISTS idx_task_video
  ON monkey_crucible.task (video_id)
  WHERE video_id IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Note: public.task (old system) and monkey_crucible.task (Crucible) coexist
-- during the transition period. No compatibility view is created here.
-- When the old system is retired:
--   DROP TABLE public.task CASCADE;
--   CREATE VIEW public.task AS SELECT * FROM monkey_crucible.task;
-- ---------------------------------------------------------------------------
