-- =============================================================================
-- crucible — monkey_crucible.task_step_log
-- =============================================================================
-- Per-execution audit trail. One row per step attempt (success, failure,
-- skip, or timeout). Replaces free-form public.process_log for task events.
-- Run order: 006 (depends on 001 processor, 004 workflow_step, 005 task)
-- =============================================================================

CREATE TABLE IF NOT EXISTS monkey_crucible.task_step_log (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id       BIGINT      NOT NULL REFERENCES monkey_crucible.task(id) ON DELETE CASCADE,
  step_id       BIGINT      NOT NULL REFERENCES monkey_crucible.workflow_step(id),
  processor_id  BIGINT      REFERENCES public.processor(id),
  attempt       INT         NOT NULL DEFAULT 1,
  status        TEXT        NOT NULL
    CHECK (status IN ('success','failed','skipped','timeout')),
  started_at    TIMESTAMPTZ NOT NULL,
  completed_at  TIMESTAMPTZ,
  duration_ms   INT,
  result        JSONB,
  error         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_task_step_log_task
  ON monkey_crucible.task_step_log (task_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_task_step_log_step
  ON monkey_crucible.task_step_log (step_id);

CREATE INDEX IF NOT EXISTS idx_task_step_log_processor
  ON monkey_crucible.task_step_log (processor_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_task_step_log_failures
  ON monkey_crucible.task_step_log (status)
  WHERE status IN ('failed','timeout');
