-- =============================================================================
-- monkey-vault — public.processor reference
-- =============================================================================
-- This table lives in the public schema and is shared across all applications.
-- monkey-vault extends it with a slug column used as PROCESSOR_ID in .env.
--
-- Full table structure (for reference — do not recreate if table already exists):
-- =============================================================================

CREATE TABLE public.processor (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMP WITHOUT TIME ZONE NULL DEFAULT now(),
  name        TEXT NULL,
  metadata    JSONB NULL,       -- legacy: previously used to store mount paths
  enabled     BOOLEAN NULL DEFAULT true,
  breaker     BOOLEAN NULL DEFAULT false,
  in_progress BOOLEAN NULL DEFAULT false,
  ip_address  TEXT NULL,
  repository  BOOLEAN NULL DEFAULT false,

  -- Added by monkey-vault (migration 007)
  -- Matches the PROCESSOR_ID value in each vault instance's .env
  slug        TEXT UNIQUE NULL,

  CONSTRAINT processor_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_processor_slug ON public.processor(slug);

-- =============================================================================
-- Column reference
-- =============================================================================
-- id          — auto-increment PK, used as FK in monkey_vault.storage_processor_mounts
-- slug        — vault identifier, e.g. "mac-fabricio", "athens-server"
-- name        — human-readable label
-- ip_address  — informational, the machine's IP
-- enabled     — whether this processor is active
-- breaker     — circuit breaker flag (halt processing)
-- in_progress — whether this processor is currently handling a task
-- repository  — whether this processor has repo access
-- metadata    — legacy JSONB, previously held mount paths (replaced by storage_processor_mounts)
-- =============================================================================

-- To add slug to an existing processor table (already run in migration 007):
-- ALTER TABLE public.processor ADD COLUMN IF NOT EXISTS slug TEXT UNIQUE;
